version: '2.2'
services:
  akka-serverless-proxy-dc-1:
    image: docker.io/jpollock/akkaserverless-proxy-postgres:latest
    command: -Dconfig.resource=postgres-dev-mode-A.conf -Dakka.persistence.r2dbc.connection-factory.host=castor.db.elephantsql.com
    ports:
      - "10000:10000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      DB_DATABASE: wkogdncn
      DB_USER: wkogdncn
      DB_PASSWORD: A7XsVyn64jzI4Euvgfmr478lwRHqdeN-
    # depends_on: 
    #   - postgres-dc-1
  # postgres-dc-1:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  # akka-serverless-proxy-dc-2:
  #   image: gcr.io/cloudstateengine/akkaserverless-proxy-postgres:latest
  #   command: -Dconfig.resource=postgres-dev-mode-B.conf -Dakka.persistence.r2dbc.connection-factory.host=castor.db.elephantsql.com
  #   ports:
  #     - "10001:10001"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
  #     USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
  #     DB_DATABASE: wkogdncn
  #     DB_USER: wkogdncn
  #     DB_PASSWORD: A7XsVyn64jzI4Euvgfmr478lwRHqdeN-
  #   depends_on: 
  #     - postgres-dc-2
  # postgres-dc-2:
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
